# Generated by Django 3.2.25 on 2025-06-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkrep', '0006_subscriberproductrate'),
    ]

    operations = [
        # Add indexes for Usagereport table to improve dashboard performance
        # SQL Server compatible syntax
        migrations.RunSQL(
            """
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_usagereport_detailsvieweddate')
            CREATE INDEX idx_usagereport_detailsvieweddate ON usagereport (DetailsViewedDate);
            """,
            reverse_sql="DROP INDEX IF EXISTS usagereport.idx_usagereport_detailsvieweddate;"
        ),
        migrations.RunSQL(
            """
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_usagereport_subscribername')
            CREATE INDEX idx_usagereport_subscribername ON usagereport (SubscriberName);
            """,
            reverse_sql="DROP INDEX IF EXISTS usagereport.idx_usagereport_subscribername;"
        ),
        migrations.RunSQL(
            """
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_usagereport_productname')
            CREATE INDEX idx_usagereport_productname ON usagereport (ProductName);
            """,
            reverse_sql="DROP INDEX IF EXISTS usagereport.idx_usagereport_productname;"
        ),
        migrations.RunSQL(
            """
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_usagereport_date_subscriber')
            CREATE INDEX idx_usagereport_date_subscriber ON usagereport (DetailsViewedDate, SubscriberName);
            """,
            reverse_sql="DROP INDEX IF EXISTS usagereport.idx_usagereport_date_subscriber;"
        ),
        migrations.RunSQL(
            """
            IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_usagereport_date_product')
            CREATE INDEX idx_usagereport_date_product ON usagereport (DetailsViewedDate, ProductName);
            """,
            reverse_sql="DROP INDEX IF EXISTS usagereport.idx_usagereport_date_product;"
        ),
    ]
